version: '3.3'

volumes:
  db-data:
  evolution-instances:
  pgadmin_data:
  evolution_redis:
  chatwoot_storage:
  chatwoot_postgres:
  chatwoot_redis:

networks:
  typebot-network:
    driver: bridge

services:
  # Chatwoot Services
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - chatwoot_storage:/app/storage
    networks:
      - typebot-network

  rails:
    <<: *base
    depends_on:
      - postgres-db
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres-db
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  # Typebot Services
  postgres-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - chatwoot_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=typebot
    networks:
      - typebot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=contato@tarciso.dev
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4001:80
    networks:
      - typebot-network

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - '8081:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: ../typebot/.env
    networks:
      - typebot-network

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
    ports:
      - '8082:3000'
    env_file: ../typebot/.env
    networks:
      - typebot-network

  # Evolution API
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ../evolution/.env
    volumes:
      - evolution-instances:/evolution/instances
    networks:
      - typebot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Redis Service (Shared between Chatwoot, Typebot, and Evolution API)
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    command: >
      redis-server --port 6379 --requirepass "$REDIS_PASSWORD" --appendonly yes
    env_file: .env
    volumes:
      - evolution_redis:/data
      - chatwoot_redis:/data
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - typebot-network
