version: '3.3'

volumes:
  db-data:
  evolution-instances:
  # postgres_data:
  pgadmin_data:
  evolution_redis:

networks:
  typebot-network:
    driver: bridge

services:
  # Banco de Dados PostgreSQL para o Typebot
  typebot-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=typebot
    networks:
      - typebot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Banco de Dados PostgreSQL para o Evolution API
  # postgres:
  #   container_name: postgres
  #   image: postgres:15
  #   command: ["postgres", "-c", "max_connections=1000"]
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=typebot
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=typebot
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - typebot-network
  #   expose:
  #     - 5432

  # PgAdmin para gerenciar o banco de dados PostgreSQL do Evolution API
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=contato@tarciso.dev
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4001:80 # Alterado para evitar conflito
    networks:
      - typebot-network

  # Builder do Typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      typebot-db:
        condition: service_healthy
    ports:
      - '8081:3000' # Porta ajustada para evitar conflitos
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    networks:
      - typebot-network

  # Viewer do Typebot
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    ports:
      - '8082:3000'
    env_file: .env
    networks:
      - typebot-network
  
  # Evolution API
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080" # Porta padrão 8080
    env_file:
      - .env.evolution
    volumes:
      - evolution-instances:/evolution/instances
    networks:
      - typebot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  # Evolution Redis
  redis:
    image: redis:latest
    networks:
      - typebot-network
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379
